### ISSUE TITLE
Idea: ToDo list

### ISSUE THREAD

**Issue by poudenes** [soloam/ha-fireflyiii-integration#1]
Hi there,

I love the start of this add-on. Maybe it's an idea to create a ToDo list?
It popped up because I wanted to add the return piggy banks and invoices but no entities are created.

So I thought maybe this is not implemented yet.

**Comment by soloam** [comment]
Hello, thank you! Piggy Banks and Invoices are still being ideveloped, I'll add a todo list to the Readme so that everyone knows what to expect when running the integration! 🙂

**Comment by soloam** [comment]
Done! I added the beta roadmap to the Readme! I'll be updating it with new items with the ones that are implemented. Tks @poudenes 

The commit 7a6f710 solved the issue
