### ISSUE TITLE
First day of months all Piggy banks are clear no entities in HA

### ISSUE THREAD

**Issue by poudenes** [soloam/ha-fireflyiii-integration#3]
Hi,

All piggy banks will start over because of 1st of month. I have 22 piggy banks.
Removed all integrations. restart HA and add just the Piggy bank part.

Only have 1 entity (the status one)

No errors in log.

**Comment by poudenes** [comment]
My fault. There is only a "Last Month" option and not a "This month"
That make sense. Last month everything was paid... Would be nice to have a "This Month"

**Comment by soloam** [comment]
A this month? All options are relative to today! If you select month, it will ask when does the month start for you! If you say day 1 it will make always form day 1 to the end of the month! Reseting the values at day 1. If you say day 10 for example, it will start the month on the last day 10, and assume until the last second of day 9

Probably what's happening is that today is day 1, and you started the month on day 1, and I still have to make the code to restart the sensors. So if you configured the integration yesterday it will be assuming only the month of April.

Does that makes sense?

**Comment by soloam** [comment]
I will add to a sensor, or add as attribute, the dates that are being controlled! To help understand the time ranges

**Comment by poudenes** [comment]
<img width="165" alt="Screenshot 2024-05-01 at 12 19 38" src="https://github.com/soloam/ha-fireflyiii-integration/assets/4399532/57d7953a-1c14-45df-8a26-0ae364e73fca">

From my perspective I read this:

Last Year: 2023
Last Month: April
Last week: Week number 17
Today: Just Piggy banks for today (01-05-2024)
Custom:  

<img width="312" alt="Screenshot 2024-05-01 at 12 21 44" src="https://github.com/soloam/ha-fireflyiii-integration/assets/4399532/3a094ff3-5bc5-4047-b56a-49ac0b373426">

I think go back X days.

That's why i suggest "This month" It will show all Piggy Banks for this month (May) paid and unpaid.

If someone have also the "Last Month" you can create a second entry

**Comment by soloam** [comment]
Now in release [0.0.7](https://github.com/soloam/ha-fireflyiii-integration/releases/tag/0.0.7) it's possible to select:

- Last Year
- Last Month
- Last Week
- Yesterday

This is a addition to the existing, and now renamed:

- This Year
- This Month
- This Week
- Today

In the server sensor, it's available the information (as attribute) from the data that will be pulled
